#
#spring:
#  datasource:
#    username: root
#    password: 123456
#    # url: jdbc:mysql//47.110.248.149:3306/mybatisPlus-test?characterEncoding=utf-8&&useSSL=false&&serverTimezone=UTC
#    # 1、serverTimezone是配置时间区域
#    # 2、url 配置规则 jdbc:mysql:// + ip地址 + 端口 / 数据库名字 ? 字符编码 && 是否使用SSL && 时间区域
#    # 3、useSSL MySQL在高版本需要指明是否进行SSL连接
#    url: jdbc:mysql//47.110.248.149:3306/mybatisPlus-test?characterEncoding=utf-8&&useSSL=false&&serverTimezone=UTC  # mysql04
#
#    #    注意SpringBoot版本在2.0以前和2.0以后的配置有一些不同
#    #    driver-class-name: com.mysql.jdbc.Driver SpringBoot 2.0以前的版本
#    driver‐class‐name: com.mysql.cj.jdbc.Driver
#
#
